import { Candle } from "./twelvedata";
import { rsi, trendBias } from "./indicators";

export type MmrSetup = {
  direction: "bullish" | "bearish";
  impulseLow: number;
  impulseHigh: number;
  range: number;
  mmrEntry: number;
  currentPrice: number;
  distancePct: number; // how far current price is from the MMR entry, in %
};

/**
 * Finds the most recent clean impulse leg in the given candles and
 * derives the MMR entry level: entry = high - (range / 2.6) for a
 * bullish impulse, or entry = low + (range / 2.6) for a bearish one.
 *
 * "Clean impulse" here = the largest single directional swing (peak
 * to trough or trough to peak) within the lookback window, used as a
 * simple proxy for "one clear thrust" per your reference material.
 */
export function findMmrSetup(candles: Candle[]): MmrSetup | null {
  if (candles.length < 10) return null;

  let bestSwing = { start: 0, end: 0, size: 0, dir: "bullish" as "bullish" | "bearish" };

  for (let i = 0; i < candles.length; i++) {
    for (let j = i + 1; j < candles.length; j++) {
      const up = candles[j].high - candles[i].low;
      const down = candles[i].high - candles[j].low;
      if (up > bestSwing.size) {
        bestSwing = { start: i, end: j, size: up, dir: "bullish" };
      }
      if (down > bestSwing.size) {
        bestSwing = { start: i, end: j, size: down, dir: "bearish" };
      }
    }
  }

  if (bestSwing.size <= 0) return null;

  const currentPrice = candles[candles.length - 1].close;

  if (bestSwing.dir === "bullish") {
    const impulseLow = candles[bestSwing.start].low;
    const impulseHigh = candles[bestSwing.end].high;
    const range = impulseHigh - impulseLow;
    const mmrEntry = impulseHigh - range / 2.6;
    const distancePct = (Math.abs(currentPrice - mmrEntry) / mmrEntry) * 100;
    return {
      direction: "bullish",
      impulseLow,
      impulseHigh,
      range,
      mmrEntry,
      currentPrice,
      distancePct
    };
  } else {
    const impulseHigh = candles[bestSwing.start].high;
    const impulseLow = candles[bestSwing.end].low;
    const range = impulseHigh - impulseLow;
    const mmrEntry = impulseLow + range / 2.6;
    const distancePct = (Math.abs(currentPrice - mmrEntry) / mmrEntry) * 100;
    return {
      direction: "bearish",
      impulseLow,
      impulseHigh,
      range,
      mmrEntry,
      currentPrice,
      distancePct
    };
  }
}

export type ScoredSignal = {
  symbol: string;
  score: number; // 0-100
  setup: MmrSetup;
  higherTfBias: "bullish" | "bearish" | "flat";
  rsiValue: number;
  alignedWithHigherTf: boolean;
};

/**
 * Rule-based 0-100 score. This is deliberately NOT generated by the
 * LLM — it's a transparent weighted sum so the number is reproducible
 * and explainable, matching your reference material's own checklist:
 *   - clean impulse (bigger weight if the swing is a clean, dominant move)
 *   - price proximity to the MMR level (closer = higher score)
 *   - higher-timeframe trend alignment (per "it's a guide, not a rule" —
 *     pullback should be WITH the higher-TF trend, not against it)
 *   - RSI not already deeply overbought/oversold against the setup
 */
export function scoreSetup(params: {
  lowerTfSetup: MmrSetup;
  higherTfCandles: Candle[];
  lowerTfCloses: number[];
}): { score: number; higherTfBias: "bullish" | "bearish" | "flat"; rsiValue: number; alignedWithHigherTf: boolean } {
  const { lowerTfSetup, higherTfCandles, lowerTfCloses } = params;

  const higherTfBias = trendBias(higherTfCandles);
  const rsiValue = rsi(lowerTfCloses);

  const alignedWithHigherTf =
    higherTfBias === "flat" ? false : higherTfBias === lowerTfSetup.direction;

  // Proximity score: 100 if price is at the MMR level, decaying as it
  // moves away. Anything beyond ~1% away scores ~0 on this component.
  const proximityScore = Math.max(0, 100 - lowerTfSetup.distancePct * 100);

  // Trend alignment: big weight, since a pullback against the higher
  // timeframe trend is exactly the "weak move that pulls back deeper"
  // failure case called out in the reference material.
  const alignmentScore = alignedWithHigherTf ? 100 : higherTfBias === "flat" ? 40 : 0;

  // RSI sanity check: for a bullish setup we don't want RSI already
  // deeply overbought (>75) at the entry; symmetric for bearish/<25.
  let rsiScore = 100;
  if (lowerTfSetup.direction === "bullish" && rsiValue > 75) rsiScore = 30;
  if (lowerTfSetup.direction === "bearish" && rsiValue < 25) rsiScore = 30;

  const score =
    proximityScore * 0.45 + alignmentScore * 0.4 + rsiScore * 0.15;

  return {
    score: Math.round(Math.max(0, Math.min(100, score))),
    higherTfBias,
    rsiValue: Math.round(rsiValue * 10) / 10,
    alignedWithHigherTf
  };
                     }
